### ISSUE TITLE
@DainIronfoot Bug

### ISSUE THREAD

**Issue by FreezePhoenix** [Hosch250/CheckersWebsite#3]
When you start a game from a FEN, like so:
![screenshot 2018-05-07 at 7 49 33 am](https://user-images.githubusercontent.com/24441367/39700441-375c9048-51cb-11e8-9041-7751f96ed5c5.png)
It still forces black to move upwards, like so: 
![screenshot 2018-05-07 at 7 50 24 am](https://user-images.githubusercontent.com/24441367/39700474-583e6354-51cb-11e8-8443-b7fe06c46082.png)
When it should have black move down.

**Comment by Hosch250** [comment]
That's not a bug. Each square is assigned a specific number behind the scenes, and you just assigned a bunch of them to the wrong squares. I don't have the resources to determine if a board is valid (although I could mark boards as invalid that have checkers in the king row, I suppose), so I decided that if the user creates an invalid board, that's their problem.

**Comment by Hosch250** [comment]
Clarified on the comments--this is indeed a bug.
